### ISSUE TITLE
Bumping upper bounds on dormouse-uri

### ISSUE THREAD

**Issue by maurges** [TheInnerLight/dormouse#11]
I'm currently using dormouse-uri in a project, and it works well with:
- ghc 9.4.7 
- bytestring-0.11.5.2
- attoparsec-0.14.4

But requires me to specify allow-newer: true. Would be nice to have updated bounds in hackage as well. I can submit a patch to this repo if you would like.

**Comment by TheInnerLight** [comment]
Done in 0.3
