### ISSUE TITLE
Hackage docs failed to build for doormouse-client-0.1.0.0

### ISSUE THREAD

**Issue by seagreen** [TheInnerLight/dormouse#5]
Not sure what the problem is because I was able to build them locally.

PS: Thanks for the new library, excited to see where it goes!

**Comment by TheInnerLight** [comment]
The Hackage documentation mentions that this can happen, seemingly for no particular reason.

There is a manual process to include the docs in the package, I will investigate and see if I can upload a fixed version.

**Comment by mitchellwrosen** [comment]
The build failed due to missing `Lift Text` instances: https://hackage.haskell.org/package/dormouse-client-0.1.0.0/reports/2

These instances were only added in `text-1.2.4.0`, so the lower bound of the dependency on `text` should be bumped

**Comment by TheInnerLight** [comment]
Thanks @mitchellwrosen, just realised this as well.  Fixing now.

**Comment by TheInnerLight** [comment]
A new version has now been published and module documentation has been successfully built in Hackage.  Thanks both.
